# Generated by Django 3.0.6 on 2020-06-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_portcat_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
