# Generated by Django 3.0.6 on 2020-06-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
