# Generated by Django 3.0.6 on 2020-06-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='technologies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
